version: '3.8'

services:
  bot:
    build: .
    container_name: garage_bot
    volumes:
      - ./garazhka.db:/app/garazhka.db # Монтируем базу данных для сохранения данных
    environment:
      - PYTHONUNBUFFERED=1
    restart: always